export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = '"GET_CUSTOMER_SUCCESS"';
export const GET_CUSTOMER_FAILED = "GET_CUSTOMER_FAILED";
export const GET_CUSTOMER_REQUEST = "GET_PRODUCTS_REQUEST";
