export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = '"GET_CUSTOMER_SUCCESS"';
export const GET_CUSTOMER_FAILED = "GET_CUSTOMER_FAILED";
export const GET_CUSTOMER_REQUEST = "GET_PRODUCTS_REQUEST";

export const DELETE_SALES_RECORD = "DELETE_SALES_RECORD";
export const DELETE_SALES_RECORD_SUCCESS = '"DELETE_SALES_RECORD_SUCCESS"';
export const DELETE_SALES_RECORD_FAILED = "DELETE_SALES_RECORD_FAILED";
export const DELETE_SALES_RECORD_REQUEST = "DELETE_SALES_RECORD_REQUEST";

export const ADD_SALES_RECORD = "ADD_SALES_RECORD";
export const EDIT_SALES_RECORD = "EDIT_SALES_RECORD";

export const SET_FILTER = "SET_FILTER";
